// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eextrvidcxsgzjpbryvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleHRydmlkY3hzZ3pqcGJyeXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjUxOTUsImV4cCI6MjA1NDcwMTE5NX0.I1rtLlemSXbQkWJWbqVo4_wVh-pZDR8vCEYCvGoDb3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);